title: artXchemistry
email: contact@artxchemistry.com
description: "Analog photography by Paul Glover. (c) 2024 All Rights Reserved."
baseurl: ""
url: ""

theme: minima
plugins:
  - jekyll-feed

defaults:
  -
   scope:
     path: "posts"
   values:
     layout: "post"
     author: "Paul Glover"

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
